l = Location.create(name: "New York City")
l.recordings.create(temperature: 32, status: "cloudy")
l.recordings.create(temperature: 34, status: "rainy")
l.recordings.create(temperature: 30, status: "rainy")
l.recordings.create(temperature: 30, status: "cloudy")
l.recordings.create(temperature: 28, status: "sunny")